### PR TITLE
make usbmount play nicely with systemd with the addition of a systemd…

### PR DESCRIPTION
**Pull request by joolswills**
… service - as per https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774149#177

rename usbmount.rules to 90-usbmount.rules
updated changelog

### CODE REVIEW

**Comment by rbrito** [comment]
@joolswills, I merged another pull request before yours (https://github.com/rbrito/usbmount/pull/3) and your pull request doesn't apply cleanly anymore.

Can you resubmit it, please?

Also, please take a look at https://github.com/rbrito/usbmount/pull/3#issuecomment-341261178 and let me know if you are interested.

**Comment by rbrito** [comment]
Dear @joolswills,

Can you please review the code that I just merged? Do you want to adopt the package?

Thanks,

Rogério Brito.

**Comment by joolswills** [comment]
Slightly different service from mine (more config in there). I'm no systemd expert though, so if it works, I'm sure it's ok. I don't have time I'm afraid to help with development currently. Too many other projects. Cheers!

**Comment by rbrito** [comment]
OK, I'm closing this, then.

A pity that you can't adopt the package. I guess that I will offer it on debian planet for adoption.

Thanks.

**Pull request closed without merging**
